In [21]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np 
import seaborn as sns

In [22]:
df=pd.read_csv(r"C:\DESKTOP_FILES\project\data\survey_results_public.csv")
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

In [23]:
for column in df.columns:
    print (column)

ResponseId
MainBranch
Age
Employment
RemoteWork
Check
CodingActivities
EdLevel
LearnCode
LearnCodeOnline
TechDoc
YearsCode
YearsCodePro
DevType
OrgSize
PurchaseInfluence
BuyNewTool
BuildvsBuy
TechEndorse
Country
Currency
CompTotal
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DatabaseAdmired
PlatformHaveWorkedWith
PlatformWantToWorkWith
PlatformAdmired
WebframeHaveWorkedWith
WebframeWantToWorkWith
WebframeAdmired
EmbeddedHaveWorkedWith
EmbeddedWantToWorkWith
EmbeddedAdmired
MiscTechHaveWorkedWith
MiscTechWantToWorkWith
MiscTechAdmired
ToolsTechHaveWorkedWith
ToolsTechWantToWorkWith
ToolsTechAdmired
NEWCollabToolsHaveWorkedWith
NEWCollabToolsWantToWorkWith
NEWCollabToolsAdmired
OpSysPersonal use
OpSysProfessional use
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
OfficeStackAsyncAdmired
OfficeStackSyncHaveWorkedWith
OfficeStackSyncWantToWorkWith
OfficeStackSyncAdmired
AISearchDevHaveWorkedWith
AISearchDevWantToWorkWith
AISearchDevAdmired
NEWSOSites
SOVisitFreq
SOAccount
SOPartFreq
SOHow
SOComm
AISelect
AISent
AIBen
AIAcc
AIComplex
AIToolCurrently Using
AIToolInterested in Using
AIToolNot interested in Using
AINextMuch more integrated
AINextNo change
AINextMore integrated
AINextLess integrated
AINextMuch less integrated
AIThreat
AIEthics
AIChallenges
TBranch
ICorPM
WorkExp
Knowledge_1
Knowledge_2
Knowledge_3
Knowledge_4
Knowledge_5
Knowledge_6
Knowledge_7
Knowledge_8
Knowledge_9
Frequency_1
Frequency_2
Frequency_3
TimeSearching
TimeAnswering
Frustration
ProfessionalTech
ProfessionalCloud
ProfessionalQuestion
Industry
JobSatPoints_1
JobSatPoints_4
JobSatPoints_5
JobSatPoints_6
JobSatPoints_7
JobSatPoints_8
JobSatPoints_9
JobSatPoints_10
JobSatPoints_11
SurveyLength
SurveyEase
ConvertedCompYearly
JobSat

In [24]:
#age,yearscode,yearscode pro , devtype , workexp , convcompyearly(salary)
df.shape

(65437, 114)

In [25]:
df=df[["Age","YearsCodePro","DevType","WorkExp","ConvertedCompYearly"]]
df.head()

,Age,YearsCodePro,DevType,WorkExp,ConvertedCompYearly
0,Under 18 years old,NaN,NaN,NaN,NaN
1,35-44 years old,17,"Developer, full-stack",17.0,NaN
2,45-54 years old,27,Developer Experience,NaN,NaN
3,18-24 years old,NaN,"Developer, full-stack",NaN,NaN
4,18-24 years old,NaN,"Developer, full-stack",NaN,NaN

In [26]:
df = df.rename({"ConvertedCompYearly":"Salary"}, axis=1)
df.head()

                  Age YearsCodePro                DevType  WorkExp  Salary
0  Under 18 years old          NaN                    NaN      NaN     NaN
1     35-44 years old           17  Developer, full-stack     17.0     NaN
2     45-54 years old           27   Developer Experience      NaN     NaN
3     18-24 years old          NaN  Developer, full-stack      NaN     NaN
4     18-24 years old          NaN  Developer, full-stack      NaN     NaN

In [27]:
df=df.dropna(subset=["Salary"])
df["Salary"].isnull().sum()

0

In [28]:
df.dtypes

Age              object
YearsCodePro     object
DevType          object
WorkExp         float64
Salary          float64
dtype: object

In [30]:
df["YearsCodePro"].unique()

array(['1', '6', '17', '7', '18', '25', '30', '20', '50', '27', '16', '4',
       '15', '11', '23', '10', '9', '8', '24', '12', '26', '40',
       'Less than 1 year', '14', '22', '5', '28', '3', '44', '42', '13',
       '19', '2', '35', '31', '41', '36', nan, '38', '32', '34', '21',
       'More than 50 years', '29', '45', '43', '37', '33', '48', '39',
       '46', '49', '47'], dtype=object)

In [31]:
def fix(x):
    if x=="More than 50 years":
        return 50
    if x=="Less than 1 year":
        return 0.5
df["YearsCodePro"]=df["YearsCodePro"].apply(fix)
df.dtypes

Age              object
YearsCodePro    float64
DevType          object
WorkExp         float64
Salary          float64
dtype: object

In [32]:
df.isnull().sum()

Age                 0
YearsCodePro    22764
DevType            32
WorkExp          7291
Salary              0
dtype: int64

In [33]:
df=df.dropna()
df.isnull().sum()

Age             0
YearsCodePro    0
DevType         0
WorkExp         0
Salary          0
dtype: int64

In [37]:
x=df.drop("Salary",axis=1)
y=df["Salary"]

In [45]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
x["Age"]=lb.fit_transform(x["Age"])
x["DevType"]=lb.fit_transform(x["DevType"])
x

       Age  YearsCodePro  DevType  WorkExp
542      0           0.5       15      0.0
654      0           0.5       12      1.0
770      0           0.5       15      1.0
1019     4          50.0       15     50.0
1020     1           0.5       15      1.0
...    ...           ...      ...      ...
40563    0           0.5       15      1.0
40736    4          50.0       22     50.0
40779    0           0.5       12      1.0
41040    0           0.5       17      1.0
41174    0           0.5       15      0.0

[366 rows x 4 columns]

In [46]:
x.dtypes

Age               int64
YearsCodePro    float64
DevType           int64
WorkExp         float64
dtype: object