In [1]:
import numpy as np 
import pandas as pd
import  matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data=pd.read_csv(r"C:\DESKTOP_FILES\project\data\survey_results_public.csv")
data.head

<bound method NDFrame.head of        ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65432       65433  I am a developer by profession     18-24 years old
65433       65434  I am a developer by profession     25-34 years old
65434       65435  I am a developer by profession     25-34 years old
65435       65436  I am a developer by profession     18-24 years old
65436       65437     I code primarily as a hobby     18-24 years old

                Employment                            RemoteWork   Check  \
0      Employed, full-time                                Remote  Apples
1      Employed, full-time                                Remote  Apples
2      Employed, full-time                                Remote  Apples
3       Student, full-time                                   NaN  Apples
4       Student, full-time                                   NaN  Apples
...                    ...                                   ...     ...
65432  Employed, full-time                                Remote  Apples
65433  Employed, full-time                                Remote  Apples
65434  Employed, full-time                             In-person  Apples
65435  Employed, full-time  Hybrid (some remote, some in-person)  Apples
65436   Student, full-time                                   NaN  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65432                      Hobby;School or academic work
65433           Hobby;Contribute to open-source projects
65434                                              Hobby
65435  Hobby;Contribute to open-source projects;Profe...
65436                                                NaN

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65432       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65433                                                NaN
65434       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...
65436                                                NaN

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65432  On the job training;School (i.e., University, ...
65433                                                NaN
65434  Other online resources (e.g., videos, blogs, f...
65435  On the job training;Other online resources (e....
65436                                                NaN

                                         LearnCodeOnline  ... JobSatPoints_6  \
0                                                    NaN  ...            NaN
1      Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2      Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3      Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4      Technical documentation;Blogs;Written Tutorial...  ...            NaN
...                                                  ...  ...            ...
65432                                                NaN  ...            NaN
65433                                                NaN  ...            NaN
65434  Technical documentation;Stack Overflow;Social ...  ...            NaN
65435  Technical documentation;Blogs;Written Tutorial...  ...            0.0
65436                                                NaN  ...            NaN

      JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0                NaN            NaN            NaN             NaN
1                0.0            0.0            0.0             0.0
2                NaN            NaN            NaN             NaN
3                NaN            NaN            NaN             NaN
4                NaN            NaN            NaN             NaN
...              ...            ...            ...             ...
65432            NaN            NaN            NaN             NaN
65433            NaN            NaN            NaN             NaN
65434            NaN            NaN            NaN             NaN
65435            0.0            0.0            0.0             0.0
65436            NaN            NaN            NaN             NaN

      JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly  \
0                 NaN                    NaN        NaN                 NaN
1                 0.0                    NaN        NaN                 NaN
2                 NaN  Appropriate in length       Easy                 NaN
3                 NaN               Too long       Easy                 NaN
4                 NaN              Too short       Easy                 NaN
...               ...                    ...        ...                 ...
65432             NaN                    NaN        NaN                 NaN
65433             NaN                    NaN        NaN                 NaN
65434             NaN                    NaN        NaN                 NaN
65435             0.0                    NaN        NaN                 NaN
65436             NaN                    NaN        NaN                 NaN

      JobSat
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
65432    NaN
65433    NaN
65434    NaN
65435    NaN
65436    NaN

[65437 rows x 114 columns]>

In [4]:
data.shape , data.columns

((65437, 114),
 Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check',
        'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
        ...
        'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9',
        'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase',
        'ConvertedCompYearly', 'JobSat'],
       dtype='object', length=114))

In [6]:
for col in data.columns:
    print(col)

ResponseId
MainBranch
Age
Employment
RemoteWork
Check
CodingActivities
EdLevel
LearnCode
LearnCodeOnline
TechDoc
YearsCode
YearsCodePro
DevType
OrgSize
PurchaseInfluence
BuyNewTool
BuildvsBuy
TechEndorse
Country
Currency
CompTotal
LanguageHaveWorkedWith
LanguageWantToWorkWith
LanguageAdmired
DatabaseHaveWorkedWith
DatabaseWantToWorkWith
DatabaseAdmired
PlatformHaveWorkedWith
PlatformWantToWorkWith
PlatformAdmired
WebframeHaveWorkedWith
WebframeWantToWorkWith
WebframeAdmired
EmbeddedHaveWorkedWith
EmbeddedWantToWorkWith
EmbeddedAdmired
MiscTechHaveWorkedWith
MiscTechWantToWorkWith
MiscTechAdmired
ToolsTechHaveWorkedWith
ToolsTechWantToWorkWith
ToolsTechAdmired
NEWCollabToolsHaveWorkedWith
NEWCollabToolsWantToWorkWith
NEWCollabToolsAdmired
OpSysPersonal use
OpSysProfessional use
OfficeStackAsyncHaveWorkedWith
OfficeStackAsyncWantToWorkWith
OfficeStackAsyncAdmired
OfficeStackSyncHaveWorkedWith
OfficeStackSyncWantToWorkWith
OfficeStackSyncAdmired
AISearchDevHaveWorkedWith
AISearchDevWantToWorkWith
AISearchDevAdmired
NEWSOSites
SOVisitFreq
SOAccount
SOPartFreq
SOHow
SOComm
AISelect
AISent
AIBen
AIAcc
AIComplex
AIToolCurrently Using
AIToolInterested in Using
AIToolNot interested in Using
AINextMuch more integrated
AINextNo change
AINextMore integrated
AINextLess integrated
AINextMuch less integrated
AIThreat
AIEthics
AIChallenges
TBranch
ICorPM
WorkExp
Knowledge_1
Knowledge_2
Knowledge_3
Knowledge_4
Knowledge_5
Knowledge_6
Knowledge_7
Knowledge_8
Knowledge_9
Frequency_1
Frequency_2
Frequency_3
TimeSearching
TimeAnswering
Frustration
ProfessionalTech
ProfessionalCloud
ProfessionalQuestion
Industry
JobSatPoints_1
JobSatPoints_4
JobSatPoints_5
JobSatPoints_6
JobSatPoints_7
JobSatPoints_8
JobSatPoints_9
JobSatPoints_10
JobSatPoints_11
SurveyLength
SurveyEase
ConvertedCompYearly
JobSat

In [9]:
data = data[
[
"Country",
"EdLevel",
"YearsCodePro",
"DevType",
"OrgSize",
"Industry",
"ConvertedCompYearly"
]
]
data.head()

,Country,EdLevel,YearsCodePro,DevType,OrgSize,Industry,ConvertedCompYearly
0,United States of America,Primary/elementary school,NaN,NaN,NaN,NaN,NaN
1,United Kingdom of Great Britain and Northern I...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",17,"Developer, full-stack",NaN,NaN,NaN
2,United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",27,Developer Experience,NaN,NaN,NaN
3,Canada,Some college/university study without earning ...,NaN,"Developer, full-stack",NaN,NaN,NaN
4,Norway,"Secondary school (e.g. American high school, G...",NaN,"Developer, full-stack",NaN,NaN,NaN

In [10]:
data = data.rename({"ConvertedCompYearly": "Salary"}, axis=1)
data.head()

,Country,EdLevel,YearsCodePro,DevType,OrgSize,Industry,Salary
0,United States of America,Primary/elementary school,NaN,NaN,NaN,NaN,NaN
1,United Kingdom of Great Britain and Northern I...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",17,"Developer, full-stack",NaN,NaN,NaN
2,United Kingdom of Great Britain and Northern I...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",27,Developer Experience,NaN,NaN,NaN
3,Canada,Some college/university study without earning ...,NaN,"Developer, full-stack",NaN,NaN,NaN
4,Norway,"Secondary school (e.g. American high school, G...",NaN,"Developer, full-stack",NaN,NaN,NaN

In [12]:
data.isnull().sum()

Country          6507
EdLevel          4653
YearsCodePro    13827
DevType          5992
OrgSize         17957
Industry        36579
Salary          42002
dtype: int64

In [14]:
data = data.dropna(subset=["Salary"])
data.shape

(23435, 7)

(23435, 7)

In [17]:
data

,Country,EdLevel,YearsCodePro,DevType,OrgSize,Industry,Salary
72,Pakistan,"Secondary school (e.g. American high school, G...",1,Data scientist or machine learning specialist,100 to 499 employees,Software Development,7322.0
374,Austria,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",6,Academic researcher,100 to 499 employees,NaN,30074.0
379,Turkey,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",6,Data scientist or machine learning specialist,20 to 99 employees,Computer Systems Design and Services,91295.0
385,France,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",17,"Developer, back-end","Just me - I am a freelancer, sole proprietor, ...",NaN,53703.0
389,United States of America,Some college/university study without earning ...,7,Student,10 to 19 employees,"Transportation, or Supply Chain",110000.0
...,...,...,...,...,...,...,...
41180,Sweden,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",3,"Developer, embedded applications or devices",100 to 499 employees,Software Development,44640.0
41184,United States of America,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",30,Project manager,"1,000 to 4,999 employees",Government,170000.0
41185,United States of America,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",15,"Developer, full-stack",100 to 499 employees,NaN,116844.0
41186,United States of America,Some college/university study without earning ...,1,"Developer, full-stack",2 to 9 employees,Software Development,12000.0
41187,Switzerland,Something else,35,"Developer, embedded applications or devices",20 to 99 employees,"Internet, Telecomm or Information Services",222834.0

In [23]:
data["YearsCodePro"].dtype , data.columns.dtype

(dtype('O'), dtype('O'))

In [24]:
data["YearsCodePro"].unique()

array(['1', '6', '17', '7', '18', '25', '30', '20', '50', '27', '16', '4',
       '15', '11', '23', '10', '9', '8', '24', '12', '26', '40',
       'Less than 1 year', '14', '22', '5', '28', '3', '44', '42', '13',
       '19', '2', '35', '31', '41', '36', nan, '38', '32', '34', '21',
       'More than 50 years', '29', '45', '43', '37', '33', '48', '39',
       '46', '49', '47'], dtype=object)

In [25]:
def clean_experience(x):
    if x == "More than 50 years":
        return 50
    if x == "Less than 1 year":
        return 0.5
    return float(x)
data["YearsCodePro"] = data["YearsCodePro"].apply(clean_experience)

In [28]:
data.isnull().sum()

Country            0
EdLevel            0
YearsCodePro      90
DevType           32
OrgSize           25
Industry        7459
Salary             0
dtype: int64

In [30]:
data=data.dropna()
data.isnull().sum()

Country         0
EdLevel         0
YearsCodePro    0
DevType         0
OrgSize         0
Industry        0
Salary          0
dtype: int64

In [31]:
data.shape

(15922, 7)

In [32]:
data.dtypes

Country          object
EdLevel          object
YearsCodePro    float64
DevType          object
OrgSize          object
Industry         object
Salary          float64
dtype: object

In [33]:
data.columns.unique()

Index(['Country', 'EdLevel', 'YearsCodePro', 'DevType', 'OrgSize', 'Industry',
       'Salary'],
      dtype='object')

In [35]:
data.isnull().sum()

Country         0
EdLevel         0
YearsCodePro    0
DevType         0
OrgSize         0
Industry        0
Salary          0
dtype: int64